/**
 * CalcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const OperationTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    SUM: 'SUM',

    /**
     * TODO: Write general description for this element
     */
    SUBTRACT: 'SUBTRACT',

    /**
     * TODO: Write general description for this element
     */
    MULTIPLY: 'MULTIPLY',

    /**
     * TODO: Write general description for this element
     */
    DIVIDE: 'DIVIDE',

};

module.exports = OperationTypeEnum;
