/**
 * CalcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const Configuration = {
    // The object containing the OAuthToken
    oAuthToken: {},

    // Callback function to be called on token refresh
    // TODO: Replace the oAuthTokenUpdateCallback with an appropriate callback function
    oAuthTokenUpdateCallback: null,

    // The base Uri for API calls
    BASEURI: 'http://examples.apimatic.io/apps/calculator',

    // a
    a: 'a',

    // OAuth 2 Client ID
    // TODO: Replace the OAuthClientId with an appropriate value
    oAuthClientId: 'TODO: Replace',

    // OAuth 2 Client Secret
    // TODO: Replace the OAuthClientSecret with an appropriate value
    oAuthClientSecret: 'TODO: Replace',

    // OAuth 2 Redirection endpoint or Callback Uri
    // TODO: Replace the OAuthRedirectUri with an appropriate value
    oAuthRedirectUri: 'TODO: Replace',

};

module.exports = Configuration;
